openapi: 3.0.0
info:
  title: Delilah Restaurant App
  description: This is an API to manage manage users, orders, payment methods and products.
  version: 0.1.9
servers:
  - url: http://localhost:9090/api/v1
    description: Development server to try requests.
paths:
  /login:
    post:
      tags: 
        - Log in
      summary: Login for an user
      description: Endpoint to send login information. You can log in using username or email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: adri123
                password:
                  type: string
                  example: adri123
      responses:
        200:
          description: Response returns user's index of users array.
        400:
          description: Failed to realize login.
  /users:
    get:
      tags: 
        - Users
      summary: Get all users.
      description: Endpoint to get all registered users. It is visible to admin users only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user.
      responses:
        200:
          description: Response returns all registered users.
        404:
          description: Failed to load all registered users.
    post:
      tags: 
        - Users
      summary: Create an user
      description: Endpoint to create an user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Response returns new user information.
        404:
          description: Failed to create a new user.
  /users/products:
    get:
      tags: 
        - Products
      summary: Get all actives and fav products by user id.
      description: Endpoint to get all actives Products and user's fav products. It is visible to user only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080204721
          required: true
          description: Numeric ID of the user to be able to get products.
      responses:
        200:
          description: Response returns all active Products and user's fav products.
        404:
          description: Failed to load Products.
  /products:
    get:
      tags: 
        - Products
      summary: Get all products including inactive products.
      description: Endpoint to get all Products. It is visible to admin user only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user to be able to get users.
      responses:
        200:
          description: Response returns all Products.
        404:
          description: Failed to load Products.
    post:
      tags: 
        - Products
      summary: Create a new product.
      description: Endpoint to create a new product. It is just for admin user only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Response returns new product.
        404:
          description: Failed to create product.
  /products/{id}:
    put:
      tags: 
        - Products
      summary: Update an existing product.
      description: Endpoint to update an existing product. It is just for admin user only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user.
        - in: path
          name: id
          schema:
            type: number
            example: 1625082901706
          required: true
          description: Numeric ID of the product to be able to update it.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        200:
          description: Response returns updated product.
        404:
          description: Failed to update product.
    delete:
      tags: 
        - Products
      summary: Delete an existing product.
      description: Endpoint to delete an existing product. It is just for admin user only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user.
        - in: path
          name: id
          schema:
            type: number
            example: 1625082901706
          required: true
          description: Numeric ID of the product to be able to delete it.
      responses:
        200:
          description: Response returns a confirmation message.
        404:
          description: Failed to delete product.
  /paymentMethods:
    get:
      tags: 
        - Payment Methods
      summary: Get all existing payment method.
      description: Endpoint to get all Payment Methods. When the user id corresponds to an admin, it returns the active and inactive means of payment. When it is a common user, it returns only the active payment methods.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the user.
      responses:
        200:
          description: Response returns all Payment Methods.
        404:
          description: Failed to load all Payment Methods.
    post:
      tags: 
        - Payment Methods
      summary: Create a Payment Method
      description: Endpoint to create a Payment Method. It is just for admin user only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentMethod'
      responses:
        200:
          description: Response returns a Payment Methods object.
        404:
          description: Failed to load Payment Methods.
  /paymentMethods/{id}:
    put:
      tags: 
        - Payment Methods
      summary: Update an existing Payment Method.
      description: Endpoint to update an existing Payment Method. It is just for admin user only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user.
        - in: path
          name: id
          schema:
            type: number
            example: 1625082125742
          required: true
          description: Numeric ID of the payment method.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentMethod'
      responses:
        200:
          description: Response returns updated payment method.
        404:
          description: Failed to update payment method.
    delete:
      tags: 
        - Payment Methods
      summary: Delete an existing Payment Method.
      description: Endpoint to delete an existing Payment Method. It is just for admin user only.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user.
        - in: path
          name: id
          schema:
            type: number
            example: 1625082125742
          required: true
          description: Numeric ID of the payment method.
      responses:
        200:
          description: Response returns a confirmation message.
        404:
          description: Failed to delete payment method.
  /users/orders:
    get:
      tags: 
        - Orders (users)
      summary: Get orders history of one user.
      description: Endpoint to get orders history.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080204721
          required: true
          description: Numeric ID of the user.
      responses:
        200:
          description: Response returns an array with orders history.
        404:
          description: Failed to load orders history.
    post:
      tags: 
        - Orders (users)
      summary: Create a new order for one user.
      description: Endpoint to create a new order for one user.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080204721
          required: true
          description: Numeric ID of the user.
      responses:
        200:
          description: Response returns a confirmation message with order ID.
        404:
          description: Failed to create a new order.  
  /users/orders/{idOrder}:     
    get:
      tags: 
        - Orders (users)
      summary: Get one order identified by the provided ID.
      description: Endpoint to get one order identified by the provided ID.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080204721
          required: true
        - in: path
          name: idOrder
          schema:
            type: number
            example: 1625081464339
          required: true
          description: Numeric ID of the order.
      responses:
        200:
          description: Response returns order array if the ids are correct. If the ids do not match, it returns an empty array.
        404:
          description: Failed to load order data. It returns an empty array.
    put:
      tags: 
        - Orders (users)
      summary: Add or update a product in detail array.
      description: Endpoint to add a new product to detail array or update an existing product in detail array.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080204721
          required: true
        - in: header
          name: idprod
          schema:
            type: number
            example: 1625082848172
          required: true
        - in: header
          name: amount
          schema:
            type: number
            example: 2
            minimun: 1
          required: true
        - in: path
          name: idOrder
          schema:
            type: number
            example: 1625081464339
          required: true
          description: Numeric ID of the order.
      responses:
        200:
          description: Response returns a confirmation message.
        404:
          description: Failed to load add or update product. It returns an message.      
    delete:
      tags: 
        - Orders (users)
      summary: Delete a product in detail array.
      description: Endpoint to delete a product to detail array.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080204721
          required: true
        - in: header
          name: idprod
          schema:
            type: number
            example: 1625082848172
          required: true
        - in: path
          name: idOrder
          schema:
            type: number
            example: 1625081464339
          required: true
          description: Numeric ID of the order.
      responses:
        200:
          description: Response returns order array if the ids are correct. If the ids do not match, it returns an empty array.
        404:
          description: Failed to load order data. It returns an empty array.
  /users/orders/{idOrder}/confirm:   
    put:
      tags: 
        - Orders (users)
      summary: Confirm an order.
      description: Endpoint to confirm the order. If the address does not exist, it takes the user address of user register form.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080204721
          required: true
        - in: path
          name: idOrder
          schema:
            type: number
            example: 1625081464339
          required: true
          description: Numeric ID of the order.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        200:
          description: Response returns a confirmation message.
        404:
          description: Failed to load confirm the order. It returns a message.
  /orders:
    get:
      tags: 
        - Orders (admins)
      summary: Get all orders.
      description: Endpoint to get all orders including those that are still pending.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user.
      responses:
        200:
          description: Response returns an array including one array for each status.
        404:
          description: Failed to load orders.
  /orders/{idOrder}:
    get:
      tags: 
        - Orders (admins)
      summary: Get all orders.
      description: Endpoint to get all orders including those that are still pending.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user
        - in: path
          name: idOrder
          schema:
            type: number
            example: 1625081478738
          required: true
          description: Numeric ID of the order.
      responses:
        200:
          description: Response returns order information.
        404:
          description: Failed to load order.
    put:
      tags: 
        - Orders (admins)
      summary: Update order status.
      description: Endpoint to update the status of the selected order.
      parameters:
        - in: header
          name: id
          schema:
            type: number
            example: 1625080182519
          required: true
          description: Numeric ID of the admin user
        - in: path
          name: idOrder
          schema:
            type: number
            example: 1625081478738
          required: true
          description: Numeric ID of the order.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: number
                  minimum: 1
                  maximum: 5
                  example: 5
      responses:
        200:
          description: Response returns order information with new status.
        404:
          description: Failed to update order.
components:
  schemas:
    User:
      type: object
      required:
        - username
        - name
        - email
        - phoneNumber
        - address
        - password
      properties:
        username:
          type: string
          example: adri123
        name:
          type: string
          example: Adriana Lopez 
        email:
          type: string
          format: email
          example: alopez@mail.com
        phoneNumber:
          type: number
          example: 2964635241
        address:
          type: object
          properties:
            street:
              type: string
              example: Estrada
            number:
              type: number
              example: 2020
            city:
              type: string
              example: Rio Grande  
            province:
              type: string
              example: TDF
    Product:
      required:
        - detail
        - price
      properties:
        detail:
          type: string
          example: Milanesa con pure
        price:
          type: number
          example: 350.25
        active:
          type: boolean
          example: false
          default: true
    PaymentMethod:
      required:
        - detail
      properties:
        detail:
          type: string
          example: Tarjeta de credito
    Order:
      required:
        - paymentMethod
      properties:
        paymentMethod:
          type: number
          example: 1625082031025
        address:
          type: object
          properties:
            street:
              type: string
              example: Estrada
            number:
              type: number
              example: 2020
            city:
              type: string
              example: Rio Grande  
            province:
              type: string
              example: TDF